name: Dependant Jobs

on: []

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.step1.outputs.name }}
    steps:
      - name: Job 1
        id: step1
        run: echo "name=Abdulrahman" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        env:
          NAME: ${{ needs.job1.outputs.name }}
        run: echo "Name is $NAME"
